### ISSUE TITLE
[CD] React로 구현해보기

### ISSUE THREAD

**Issue by elfinlas** [elfinlas/wanted-pre-onboarding-challenge-fe-1#1]
# Code Refactoring

현재 Next.Js 기반으로 작성되어 있는데 이 부분을 다 걷어내고 순수 React로 구현해보기

## ToDo

- [ ] 기존 코드 걷어내기
- [ ] 순수 ReactJs로 구현해보기
- [ ] 가급적 라이브러리 최소화 하기
- [ ] DaisyUI도 걷어내기
- [ ] UI/UX 고민도 같이 해보기
