### ISSUE TITLE
[Doc] ReadMe 수정 및 정리하기

### ISSUE THREAD

**Issue by elfinlas** [elfinlas/wanted-pre-onboarding-challenge-fe-1#3]
# Document

ReadMe 부분 한번 정리하기

## ToDo

- [ ] 화면 동작 부분 추가하기
- [ ] 라이브러리 적용 및 기타 내용 수정
- [ ] 구체적으로 적용한 부분에 대한 명시 처리
